### ISSUE TITLE
The homepage load time is too slow

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/www#105]
There's definitely some optimizations that can be made to make the website load faster. This issue is related to #75 & #70. 

Right now for me the page loads in about 6+ seconds. The biggest problems I can see are: 
- Many resources coming from `rethinkdb.com` that aren't loading in parallel.
- The fonts are blocking rendering of the page.
- We aren't minifying anything I believe and aren't setting proper cache headers.
- We aren't using a CDN (We can use Cloudflare for free which will also give us HTTPS #104).

https://developers.google.com/speed/pagespeed/insights/?url=www.rethinkdb.com&tab=desktop

I think with these methods we can at least get in the sub-three second mark, if not two second. 

![screenshot 2015-07-07 16 02 40](https://cloud.githubusercontent.com/assets/863286/8559449/d3806f24-24c1-11e5-93d7-28cc998d277a.png)
![screenshot 2015-07-07 16 03 06](https://cloud.githubusercontent.com/assets/863286/8559452/d53d72a8-24c1-11e5-96da-0b7586112811.png)
![screenshot 2015-07-07 16 07 24](https://cloud.githubusercontent.com/assets/863286/8559496/48ff1b56-24c2-11e5-8b8e-d2c96f5b9cf6.png)

**Comment by gabor-boros** [comment]
This load time significantly increased. Now the performance score is 100/100.
<img width="410" alt="Screenshot 2019-09-07 at 11 25 05" src="https://user-images.githubusercontent.com/19173947/64472652-2b99a300-d162-11e9-9d7d-4bbc5f5ba1ea.png">
