### ISSUE TITLE
"have a peace of mind" -> "have peace of mind. "

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/www#132]
The first paragraph on http://rethinkdb.com/services/ still reads "have a peace of mind".

To cite @chipotle:

> I'd probably say "have peace of mind."
> "A peace of mind" sounds like there are units of peace we're measuring.
> RethinkDB gives you 25% more peace of mind than MongoDB!

@mglukhovsky any thoughts?

**Comment by gabor-boros** [comment]
The page has been removed
