### ISSUE TITLE
Both `www.rethinkdb.com` and `rethinkdb.com` should redirect to the same domain

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/www#137]
Right now if I go to `www.rethinkdb.com`, the page will load and I remain at this domain. As well if I go to `rethinkdb.com` it stays at this domain. 

If you try to go to `www.twitter.com` you are redirected to `twitter.com` and if you go to `twitter.com` it stays at `twitter.com`. The same thing but the opposite with `www.google.com` and `google.com` but the action is consistent and I think we should be doing the same. 

This affects browser caching and probably other mysterious SEO side affects.

**Comment by gabor-boros** [comment]
We moved to Netlify and also set the CNAME.
