### ISSUE TITLE
Various fixes for issues identified by Google PageSpeed

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/www#171]
[Google PageSpeed shows us a few easy to fix problems](https://developers.google.com/speed/pagespeed/insights/?utm_source=analytics&tab=desktop&url=http%3A%2F%2Fwww.rethinkdb.com%2Findex.html) with rethinkdb.com.
### Cache-Control

Here's a good guide to do this: 
https://serversforhackers.com/nginx-caching/
### Etag

Not sure if there's a disadvantage to just allowing Nginx to handle etags.
http://nginx.org/en/docs/http/ngx_http_core_module.html#etag
### Optimize images
#108 #161
### Less render blocking
#170

**Comment by gabor-boros** [comment]
Because we moved to Netlify, we do not need this issue anymore. There are some best practice, seo scores what could be improved, but this will be done by some other refactoring.
