### ISSUE TITLE
Make the Jobs page live (helps the PERM process)

### ISSUE THREAD

**Issue by lindseyadavis** [rethinkdb/www#189]
We're working with an external company to ensure that our international coworkers get to stay with us. Part of this process requires us to have a Company Internet Posting; ie, a jobs page. There are other options, but they're cost prohibitive or involve a lot of effort.

Getting the Jobs page running is great for our internal recruitment, and also meets the DOL criteria for our PERM filing. Plus, it's at no cost to us. If we can get this running in 1-2 months, that would be ideal.

**Comment by gabor-boros** [comment]
The company does not exist anymore.
