### ISSUE TITLE
Wrong link highlighted in "Writing RethinkDB drivers" page

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/www#69]
On `http://rethinkdb.com/docs/writing-drivers/`, the link highlighted in the left sidebar is "Install RethinkDB server". There doesn't seem to be a link for "Writing RethinkDB drivers", but the "Writing RethinkDB drivers" page seems to be a sub-page of the "Install client drivers" page.

**Comment by gabor-boros** [comment]
Already done.
